name: RPC Code Generator CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2 UCRT64
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-ninja
            mingw-w64-ucrt-x86_64-mbedtls

      - name: Configure project
        shell: msys2 {0}
        run: |
          export PATH="/ucrt64/bin:$PATH"
          export CC=/ucrt64/bin/gcc.exe
          export CXX=/ucrt64/bin/g++.exe

          echo "Compiler:"
          which g++
          g++ --version

          echo "mbedTLS:"
          ls /ucrt64/include/mbedtls/net_sockets.h
          ls /ucrt64/lib/libmbedtls*

          rm -rf build

          cmake -S . -B build -G Ninja \
            -DCMAKE_C_COMPILER=/ucrt64/bin/gcc.exe \
            -DCMAKE_CXX_COMPILER=/ucrt64/bin/g++.exe

      - name: Build project
        shell: msys2 {0}
        run: |
          export PATH="/ucrt64/bin:$PATH"
          cmake --build build

      - name: Run code generator
        shell: msys2 {0}
        run: |
          export PATH="/ucrt64/bin:$PATH"
          ./build/app.exe proto/rpc.proto

      - name: Verify generated files
        shell: msys2 {0}
        run: |
          test -f output/UserRequest.h
          test -f output/UserRequest.c
          test -f output/UserResponse.h
          test -f output/UserResponse.c
          test -f output/UserService.h
          test -f output/UserService.cpp

          echo "All generated files exist."

      - name: Run TLS test
        shell: msys2 {0}
        run: |
          export PATH="/ucrt64/bin:$PATH"

          if [ -f build/test_tls.exe ]; then
            ./build/test_tls.exe
          else
            echo "TLS test executable was not generated."
            exit 1
          fi
